# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30ff64443781cff51f9c7b87d16569131ebbd3df3e6e91b184ba5e1af72c76f6c5977b11b27f14fcbfd6576f03e8c0db9ac59755093181d34fde4c0259fd4d20

test:
  secret_key_base: 935d312aa5b1d307a2d8394b5d15ea9ce58eb8807b17da9b4f8e1bae33ea68cb0bc84a3de71ddb6ce977460786858df2556993212e5610b2d1938b02b0a2cf86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
